ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS reserved_hard NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS quarantine NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS soft_reserved NUMERIC NOT NULL DEFAULT 0;